packages:
  - "."

allowBuilds:
  "@prisma/engines": true
  esbuild: true
  prisma: true
  sharp: true

minimumReleaseAgeExclude:
  - better-auth-evp@0.1.0 || 1.0.1 || 1.0.2 || 1.0.7
  - "@better-auth/cimd@1.7.3"
  - "@better-auth/core@1.7.3"
  - "@better-auth/drizzle-adapter@1.7.3"
  - "@better-auth/kysely-adapter@1.7.3"
  - "@better-auth/mcp@1.7.3"
  - "@better-auth/memory-adapter@1.7.3"
  - "@better-auth/mongo-adapter@1.7.3"
  - "@better-auth/oauth-provider@1.7.3"
  - "@better-auth/passkey@1.7.3"
  - "@better-auth/prisma-adapter@1.7.3"
  - "@better-auth/telemetry@1.7.3"
  - better-auth@1.7.3
