name: "Install"
description: "Sets up Node with pnpm, and installs dependencies"

runs:
  using: composite
  steps:
    - name: Install pnpm
      uses: pnpm/action-setup@v4
      with:
        version: 9

    - name: Set up Node
      uses: actions/setup-node@v4
      with:
        node-version-file: ".node-version"
        node-version: 20
        cache: pnpm

    - name: Install dependencies
      shell: bash
      run: pnpm install --frozen-lockfile
