name: Backend v2 - CI

on:
  push:
    branches: ["main"]
    paths:
      - ".github/workflows/backend_v2_ci.yaml"
      - "*"
      - "backend_v2/**"
  pull_request:
    branches: ["main"]
    paths:
      - ".github/workflows/backend_v2_ci.yaml"
      - "*"
      - "backend_v2/**"

jobs:
  lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend_v2
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      
      - name: Install bun
        uses: oven-sh/setup-bun@v2

      - name: Install deps
        run: bun install

      - name: Format
        run: bun run format

      - name: Type check
        run: bun run typecheck

      - name: Run Test Build
        run: bun run build
