name: CI

on:
  push:
    branches: ["main", "beta"]
  pull_request:
    branches: ["main", "beta"]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup node
        uses: ./.github/composite-actions/install

      - name: Lint
        run: pnpm run lint:style

      - name: Type check
        run: pnpm run lint:typecheck
        if: always()

  prettier:
    name: Format
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup node
        uses: ./.github/composite-actions/install

      - name: Format check
        run: pnpm run format:check

  # deadcode:
  #   name: Find deadcode
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v4

  #     - name: Setup node
  #       uses: ./.github/composite-actions/install

  #     - name: Find deadcode
  #       run: pnpm run knip

  build:
    name: Test build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup node
        uses: ./.github/composite-actions/install

      - name: Build
        run: pnpm run build
        env:
          USOS_CONSUMER_KEY: hello
          USOS_CONSUMER_SECRET: jello
          NEXT_PUBLIC_API_URL: http://localhost:3333
          BETTER_AUTH_SECRET: supersecret
          DATABASE_URL: ""
          NEXT_PUBLIC_SITE_URL: http://localhost:3000
